DDS Api (semi) werkend (met docker!)
Redoublet-org/Redoublet-dds pull request #1
Opened 2023-03-17 10:15 UTC by TheGoldenFyre

DDS api geïmplementeerd met behulp van de library op [de dds site](http://privat.bahnhof.se/wb758135/bridge/index.html). 

Er is wel een C# versie van deze library beschikbaar, maar die is zo verouderd dat je die niet eenvoudig draaiend kan krijgen op linux. Daarom was het enige andere alternatief gebruik maken van de C++ applicatie in combinatie met een parser in C# die alle output ervan interpreteert.

De C# applicatie is gewoon een simpele ASP.Net API met de wrapper voor de C++ DDS library (jezus wat veel afkortingen in één zin) . De C++ DDS library wordt ook gebuild in Docker, dus hier kunnen we nog op uitbreiden. Er zijn op die website ook nog wat examples beschikbaar die we kunnen gebruiken voor nieuwe functionaliteit.

Op het moment is de enige vorm van analyse die geïmplementeerd is het vinden van optimale contracten.

Dingen die nog missen:
- Unit tests voor de API en de parser
- Library functionaliteit om een volledig spel optimaal uit te spelen en te laten zien (deze functionaliteit zit wel in die verouderde C# versie, dus we zouden dat kunnen gebruiken als inspiratie)
- docker-compose zooi met aanpasbare port

2023-03-21 11:11 UTC, MatthijsdeHeus requested changes
Ziet er erg nice uit!

Ik heb nog een paar nitpicks maar voor de rest heb ik weinig aan te merken.

2023-03-21 11:23 UTC, TheGoldenFyre commented on dds-api/Program.cs
> +            if (app.Environment.IsDevelopment() || true)
Als het goed is staat er in de dockercompose file nu iets van een environment variable die ervoor zorgt dat deze if statement afgaan, we zouden kunnen overwegen twee aparte files te maken, een voor dev en een voor production?

2023-03-21 11:44 UTC, MatthijsdeHeus approved these changes

2023-03-23 15:54 UTC, rubenfranquinet requested changes
Ziet er nice uit, ook fijn om eindelijk te kunnen zeggen dat we tests hebben

2023-03-23 15:54 UTC, rubenfranquinet commented on dds-api-tests/Usings.cs
> +global using Xunit;
Is deze file met 1 regel hier echt nodig? Of kan dit ook erbij in bv ModelTests.cs

2023-03-23 15:54 UTC, rubenfranquinet commented on dds-api/ddsconfig.txt
> +C:\Users\thoma\Desktop\dds.net\source\Dds.Net.Sample\bin\Debug\Dds.Net.Sample.exe
Waarvoor is dit? Als andere hem runnen hebben ze natuurlijk een andere file locatie

2023-03-23 15:54 UTC, rubenfranquinet commented on dds-lib/examples/CalcDDtablePBN.cpp
> +  char line[80];
Uit nieuwsgierigheid, wat doet de line `char line[80];`

2023-03-23 15:54 UTC, rubenfranquinet commented on dds-lib/examples/hands.h
> +
remove whiteline

2023-03-23 15:54 UTC, rubenfranquinet commented on dds-api-tests/ModelTests.cs
WE HEBBEN TESTS!!!

2023-03-23 15:54 UTC, rubenfranquinet commented on dds-api/DDS.cs
> +                var s = process.StandardOutput.ReadLine();
Ik zou de s even een iets duidelijkere naam geven

2023-03-23 15:54 UTC, rubenfranquinet commented on dds-api/DDS.cs
> +        }
is dit automatisch gegenereerd, anders zou ik de p een iets duidelijkere naam geven

2023-03-23 15:54 UTC, rubenfranquinet commented on dds-api/DDS.cs
> +}
newline at eof

2023-03-23 15:54 UTC, rubenfranquinet commented on dds-api/Models/Card.cs
> +            return "NULL SUIT";
Moet dit niet een error geven?

2023-03-23 15:54 UTC, rubenfranquinet commented on dds-api/Models/Card.cs
> +            return "NULL VALUE";
Moet dit niet een error geven?

2023-03-27 07:40 UTC, TheGoldenFyre commented on dds-api/ddsconfig.txt
> +C:\Users\thoma\Desktop\dds.net\source\Dds.Net.Sample\bin\Debug\Dds.Net.Sample.exe
Wordt geoverride door de dockerfile om een file locatie aan te geven waarmee je de dds library kan runnen, maar aangezien dat niet echt op windows kan zal ik er wel even iets van een message neerzetten

2023-03-27 07:41 UTC, TheGoldenFyre commented on dds-lib/examples/CalcDDtablePBN.cpp
> +  char line[80];
Lijkt een buffer te zijn waar error messages naartoe kunnen worden opgeslagen, of het echt nodig is voor de functionaliteit van de code weet ik niet zeker want dit heb ik uit een voorbeeld gestolen

2023-03-27 08:42 UTC, rubenfranquinet approved these changes

2023-03-27 08:42 UTC, merged